---
- name: Ensure dependencies (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.package:
    name:
      - python3
      - python3-venv
      - python3-setuptools

- name: Ensure dependencies (RedHat)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.package:
    name:
      - python39
      - python39-setuptools
      - python39-pip

- name: Create application user
  ansible.builtin.user:
    name: leihsldap
    home: /opt/leihsldap
    system: true

- name: Install packages into virtualenv
  notify: Restart leihsldap
  ansible.builtin.pip:
    name:
      - gunicorn
      - "leihs-ldap-authenticator{{ leihs_ldap_authenticator_version }}"
    virtualenv: /opt/leihsldap/venv/
    virtualenv_command: /usr/bin/python3.9 -m venv

- name: Create leihsldap config
  notify: Restart leihsldap
  block:
    - name: Create config folder
      ansible.builtin.file:
        path: /etc/leihsldap
        state: directory
        owner: leihsldap
        group: leihsldap
        mode: "0751"
    - name: Create leihsldap config
      ansible.builtin.copy:
        content: "{{ leihs_ldap_config | to_nice_yaml(indent=2) }}"
        dest: /etc/leihsldap/leihs-ldap.yml
        owner: leihsldap
        group: leihsldap
        mode: "0640"
      no_log: true
    - name: Create gunicorn config
      ansible.builtin.template:
        src: gunicorn.conf.py.j2
        dest: /etc/leihsldap/gunicorn.conf.py
        owner: leihsldap
        group: leihsldap
        mode: "0640"

- name: Create service file
  notify:
    - Reload systemd daemon
    - Restart leihsldap
  ansible.builtin.template:
    src: leihsldap.service.j2
    dest: /etc/systemd/system/leihsldap.service
    mode: "0644"

- name: Start service
  ansible.builtin.systemd:
    name: leihsldap.service
    state: started
    enabled: true
